/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MinhaViagemRouteImport } from './routes/minha-viagem'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MinhaViagemIndexRouteImport } from './routes/minha-viagem.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MinhaViagemRoteiroRouteImport } from './routes/minha-viagem.roteiro'
import { Route as MinhaViagemPreroteiroRouteImport } from './routes/minha-viagem.preroteiro'
import { Route as MinhaViagemParceirosRouteImport } from './routes/minha-viagem.parceiros'
import { Route as MinhaViagemDocumentosRouteImport } from './routes/minha-viagem.documentos'
import { Route as AdminViagensRouteImport } from './routes/admin.viagens'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminCrmRouteImport } from './routes/admin.crm'
import { Route as AdminCrmContactIdRouteImport } from './routes/admin.crm.$contactId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaViagemRoute = MinhaViagemRouteImport.update({
  id: '/minha-viagem',
  path: '/minha-viagem',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaViagemIndexRoute = MinhaViagemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MinhaViagemRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MinhaViagemRoteiroRoute = MinhaViagemRoteiroRouteImport.update({
  id: '/roteiro',
  path: '/roteiro',
  getParentRoute: () => MinhaViagemRoute,
} as any)
const MinhaViagemPreroteiroRoute = MinhaViagemPreroteiroRouteImport.update({
  id: '/preroteiro',
  path: '/preroteiro',
  getParentRoute: () => MinhaViagemRoute,
} as any)
const MinhaViagemParceirosRoute = MinhaViagemParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => MinhaViagemRoute,
} as any)
const MinhaViagemDocumentosRoute = MinhaViagemDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => MinhaViagemRoute,
} as any)
const AdminViagensRoute = AdminViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmContactIdRoute = AdminCrmContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => AdminCrmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/minha-viagem': typeof MinhaViagemRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/crm': typeof AdminCrmRouteWithChildren
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/viagens': typeof AdminViagensRoute
  '/minha-viagem/documentos': typeof MinhaViagemDocumentosRoute
  '/minha-viagem/parceiros': typeof MinhaViagemParceirosRoute
  '/minha-viagem/preroteiro': typeof MinhaViagemPreroteiroRoute
  '/minha-viagem/roteiro': typeof MinhaViagemRoteiroRoute
  '/admin/': typeof AdminIndexRoute
  '/minha-viagem/': typeof MinhaViagemIndexRoute
  '/admin/crm/$contactId': typeof AdminCrmContactIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/crm': typeof AdminCrmRouteWithChildren
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/viagens': typeof AdminViagensRoute
  '/minha-viagem/documentos': typeof MinhaViagemDocumentosRoute
  '/minha-viagem/parceiros': typeof MinhaViagemParceirosRoute
  '/minha-viagem/preroteiro': typeof MinhaViagemPreroteiroRoute
  '/minha-viagem/roteiro': typeof MinhaViagemRoteiroRoute
  '/admin': typeof AdminIndexRoute
  '/minha-viagem': typeof MinhaViagemIndexRoute
  '/admin/crm/$contactId': typeof AdminCrmContactIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/minha-viagem': typeof MinhaViagemRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/crm': typeof AdminCrmRouteWithChildren
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/viagens': typeof AdminViagensRoute
  '/minha-viagem/documentos': typeof MinhaViagemDocumentosRoute
  '/minha-viagem/parceiros': typeof MinhaViagemParceirosRoute
  '/minha-viagem/preroteiro': typeof MinhaViagemPreroteiroRoute
  '/minha-viagem/roteiro': typeof MinhaViagemRoteiroRoute
  '/admin/': typeof AdminIndexRoute
  '/minha-viagem/': typeof MinhaViagemIndexRoute
  '/admin/crm/$contactId': typeof AdminCrmContactIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/minha-viagem'
    | '/signup'
    | '/sitemap.xml'
    | '/admin/crm'
    | '/admin/leads'
    | '/admin/viagens'
    | '/minha-viagem/documentos'
    | '/minha-viagem/parceiros'
    | '/minha-viagem/preroteiro'
    | '/minha-viagem/roteiro'
    | '/admin/'
    | '/minha-viagem/'
    | '/admin/crm/$contactId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/admin/crm'
    | '/admin/leads'
    | '/admin/viagens'
    | '/minha-viagem/documentos'
    | '/minha-viagem/parceiros'
    | '/minha-viagem/preroteiro'
    | '/minha-viagem/roteiro'
    | '/admin'
    | '/minha-viagem'
    | '/admin/crm/$contactId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/minha-viagem'
    | '/signup'
    | '/sitemap.xml'
    | '/admin/crm'
    | '/admin/leads'
    | '/admin/viagens'
    | '/minha-viagem/documentos'
    | '/minha-viagem/parceiros'
    | '/minha-viagem/preroteiro'
    | '/minha-viagem/roteiro'
    | '/admin/'
    | '/minha-viagem/'
    | '/admin/crm/$contactId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MinhaViagemRoute: typeof MinhaViagemRouteWithChildren
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-viagem': {
      id: '/minha-viagem'
      path: '/minha-viagem'
      fullPath: '/minha-viagem'
      preLoaderRoute: typeof MinhaViagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-viagem/': {
      id: '/minha-viagem/'
      path: '/'
      fullPath: '/minha-viagem/'
      preLoaderRoute: typeof MinhaViagemIndexRouteImport
      parentRoute: typeof MinhaViagemRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/minha-viagem/roteiro': {
      id: '/minha-viagem/roteiro'
      path: '/roteiro'
      fullPath: '/minha-viagem/roteiro'
      preLoaderRoute: typeof MinhaViagemRoteiroRouteImport
      parentRoute: typeof MinhaViagemRoute
    }
    '/minha-viagem/preroteiro': {
      id: '/minha-viagem/preroteiro'
      path: '/preroteiro'
      fullPath: '/minha-viagem/preroteiro'
      preLoaderRoute: typeof MinhaViagemPreroteiroRouteImport
      parentRoute: typeof MinhaViagemRoute
    }
    '/minha-viagem/parceiros': {
      id: '/minha-viagem/parceiros'
      path: '/parceiros'
      fullPath: '/minha-viagem/parceiros'
      preLoaderRoute: typeof MinhaViagemParceirosRouteImport
      parentRoute: typeof MinhaViagemRoute
    }
    '/minha-viagem/documentos': {
      id: '/minha-viagem/documentos'
      path: '/documentos'
      fullPath: '/minha-viagem/documentos'
      preLoaderRoute: typeof MinhaViagemDocumentosRouteImport
      parentRoute: typeof MinhaViagemRoute
    }
    '/admin/viagens': {
      id: '/admin/viagens'
      path: '/viagens'
      fullPath: '/admin/viagens'
      preLoaderRoute: typeof AdminViagensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm/$contactId': {
      id: '/admin/crm/$contactId'
      path: '/$contactId'
      fullPath: '/admin/crm/$contactId'
      preLoaderRoute: typeof AdminCrmContactIdRouteImport
      parentRoute: typeof AdminCrmRoute
    }
  }
}

interface AdminCrmRouteChildren {
  AdminCrmContactIdRoute: typeof AdminCrmContactIdRoute
}

const AdminCrmRouteChildren: AdminCrmRouteChildren = {
  AdminCrmContactIdRoute: AdminCrmContactIdRoute,
}

const AdminCrmRouteWithChildren = AdminCrmRoute._addFileChildren(
  AdminCrmRouteChildren,
)

interface AdminRouteChildren {
  AdminCrmRoute: typeof AdminCrmRouteWithChildren
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminViagensRoute: typeof AdminViagensRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCrmRoute: AdminCrmRouteWithChildren,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminViagensRoute: AdminViagensRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MinhaViagemRouteChildren {
  MinhaViagemDocumentosRoute: typeof MinhaViagemDocumentosRoute
  MinhaViagemParceirosRoute: typeof MinhaViagemParceirosRoute
  MinhaViagemPreroteiroRoute: typeof MinhaViagemPreroteiroRoute
  MinhaViagemRoteiroRoute: typeof MinhaViagemRoteiroRoute
  MinhaViagemIndexRoute: typeof MinhaViagemIndexRoute
}

const MinhaViagemRouteChildren: MinhaViagemRouteChildren = {
  MinhaViagemDocumentosRoute: MinhaViagemDocumentosRoute,
  MinhaViagemParceirosRoute: MinhaViagemParceirosRoute,
  MinhaViagemPreroteiroRoute: MinhaViagemPreroteiroRoute,
  MinhaViagemRoteiroRoute: MinhaViagemRoteiroRoute,
  MinhaViagemIndexRoute: MinhaViagemIndexRoute,
}

const MinhaViagemRouteWithChildren = MinhaViagemRoute._addFileChildren(
  MinhaViagemRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MinhaViagemRoute: MinhaViagemRouteWithChildren,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
