/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MinhaViagemRouteImport } from './routes/minha-viagem'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InteresseRouteImport } from './routes/interesse'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MinhaViagemIndexRouteImport } from './routes/minha-viagem.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OrcamentoTokenRouteImport } from './routes/orcamento.$token'
import { Route as MinhaViagemRoteiroRouteImport } from './routes/minha-viagem.roteiro'
import { Route as MinhaViagemPreroteiroRouteImport } from './routes/minha-viagem.preroteiro'
import { Route as MinhaViagemParceirosRouteImport } from './routes/minha-viagem.parceiros'
import { Route as MinhaViagemMapaRouteImport } from './routes/minha-viagem.mapa'
import { Route as MinhaViagemDocumentosRouteImport } from './routes/minha-viagem.documentos'
import { Route as AdminViagensRouteImport } from './routes/admin.viagens'
import { Route as AdminOrcamentosRouteImport } from './routes/admin.orcamentos'
import { Route as AdminNotificacoesRouteImport } from './routes/admin.notificacoes'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminDestinosRouteImport } from './routes/admin.destinos'
import { Route as AdminCrmRouteImport } from './routes/admin.crm'
import { Route as AdminViagensTripIdRouteImport } from './routes/admin.viagens.$tripId'
import { Route as AdminCrmContactIdRouteImport } from './routes/admin.crm.$contactId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaViagemRoute = MinhaViagemRouteImport.update({
  id: '/minha-viagem',
  path: '/minha-viagem',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InteresseRoute = InteresseRouteImport.update({
  id: '/interesse',
  path: '/interesse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaViagemIndexRoute = MinhaViagemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MinhaViagemRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OrcamentoTokenRoute = OrcamentoTokenRouteImport.update({
  id: '/orcamento/$token',
  path: '/orcamento/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaViagemRoteiroRoute = MinhaViagemRoteiroRouteImport.update({
  id: '/roteiro',
  path: '/roteiro',
  getParentRoute: () => MinhaViagemRoute,
} as any)
const MinhaViagemPreroteiroRoute = MinhaViagemPreroteiroRouteImport.update({
  id: '/preroteiro',
  path: '/preroteiro',
  getParentRoute: () => MinhaViagemRoute,
} as any)
const MinhaViagemParceirosRoute = MinhaViagemParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => MinhaViagemRoute,
} as any)
const MinhaViagemMapaRoute = MinhaViagemMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => MinhaViagemRoute,
} as any)
const MinhaViagemDocumentosRoute = MinhaViagemDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => MinhaViagemRoute,
} as any)
const AdminViagensRoute = AdminViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrcamentosRoute = AdminOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificacoesRoute = AdminNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDestinosRoute = AdminDestinosRouteImport.update({
  id: '/destinos',
  path: '/destinos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminViagensTripIdRoute = AdminViagensTripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => AdminViagensRoute,
} as any)
const AdminCrmContactIdRoute = AdminCrmContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => AdminCrmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/interesse': typeof InteresseRoute
  '/login': typeof LoginRoute
  '/minha-viagem': typeof MinhaViagemRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/crm': typeof AdminCrmRouteWithChildren
  '/admin/destinos': typeof AdminDestinosRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/viagens': typeof AdminViagensRouteWithChildren
  '/minha-viagem/documentos': typeof MinhaViagemDocumentosRoute
  '/minha-viagem/mapa': typeof MinhaViagemMapaRoute
  '/minha-viagem/parceiros': typeof MinhaViagemParceirosRoute
  '/minha-viagem/preroteiro': typeof MinhaViagemPreroteiroRoute
  '/minha-viagem/roteiro': typeof MinhaViagemRoteiroRoute
  '/orcamento/$token': typeof OrcamentoTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/minha-viagem/': typeof MinhaViagemIndexRoute
  '/admin/crm/$contactId': typeof AdminCrmContactIdRoute
  '/admin/viagens/$tripId': typeof AdminViagensTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/interesse': typeof InteresseRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/crm': typeof AdminCrmRouteWithChildren
  '/admin/destinos': typeof AdminDestinosRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/viagens': typeof AdminViagensRouteWithChildren
  '/minha-viagem/documentos': typeof MinhaViagemDocumentosRoute
  '/minha-viagem/mapa': typeof MinhaViagemMapaRoute
  '/minha-viagem/parceiros': typeof MinhaViagemParceirosRoute
  '/minha-viagem/preroteiro': typeof MinhaViagemPreroteiroRoute
  '/minha-viagem/roteiro': typeof MinhaViagemRoteiroRoute
  '/orcamento/$token': typeof OrcamentoTokenRoute
  '/admin': typeof AdminIndexRoute
  '/minha-viagem': typeof MinhaViagemIndexRoute
  '/admin/crm/$contactId': typeof AdminCrmContactIdRoute
  '/admin/viagens/$tripId': typeof AdminViagensTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/interesse': typeof InteresseRoute
  '/login': typeof LoginRoute
  '/minha-viagem': typeof MinhaViagemRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/crm': typeof AdminCrmRouteWithChildren
  '/admin/destinos': typeof AdminDestinosRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/viagens': typeof AdminViagensRouteWithChildren
  '/minha-viagem/documentos': typeof MinhaViagemDocumentosRoute
  '/minha-viagem/mapa': typeof MinhaViagemMapaRoute
  '/minha-viagem/parceiros': typeof MinhaViagemParceirosRoute
  '/minha-viagem/preroteiro': typeof MinhaViagemPreroteiroRoute
  '/minha-viagem/roteiro': typeof MinhaViagemRoteiroRoute
  '/orcamento/$token': typeof OrcamentoTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/minha-viagem/': typeof MinhaViagemIndexRoute
  '/admin/crm/$contactId': typeof AdminCrmContactIdRoute
  '/admin/viagens/$tripId': typeof AdminViagensTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/interesse'
    | '/login'
    | '/minha-viagem'
    | '/sitemap.xml'
    | '/admin/crm'
    | '/admin/destinos'
    | '/admin/leads'
    | '/admin/notificacoes'
    | '/admin/orcamentos'
    | '/admin/viagens'
    | '/minha-viagem/documentos'
    | '/minha-viagem/mapa'
    | '/minha-viagem/parceiros'
    | '/minha-viagem/preroteiro'
    | '/minha-viagem/roteiro'
    | '/orcamento/$token'
    | '/admin/'
    | '/minha-viagem/'
    | '/admin/crm/$contactId'
    | '/admin/viagens/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/interesse'
    | '/login'
    | '/sitemap.xml'
    | '/admin/crm'
    | '/admin/destinos'
    | '/admin/leads'
    | '/admin/notificacoes'
    | '/admin/orcamentos'
    | '/admin/viagens'
    | '/minha-viagem/documentos'
    | '/minha-viagem/mapa'
    | '/minha-viagem/parceiros'
    | '/minha-viagem/preroteiro'
    | '/minha-viagem/roteiro'
    | '/orcamento/$token'
    | '/admin'
    | '/minha-viagem'
    | '/admin/crm/$contactId'
    | '/admin/viagens/$tripId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/interesse'
    | '/login'
    | '/minha-viagem'
    | '/sitemap.xml'
    | '/admin/crm'
    | '/admin/destinos'
    | '/admin/leads'
    | '/admin/notificacoes'
    | '/admin/orcamentos'
    | '/admin/viagens'
    | '/minha-viagem/documentos'
    | '/minha-viagem/mapa'
    | '/minha-viagem/parceiros'
    | '/minha-viagem/preroteiro'
    | '/minha-viagem/roteiro'
    | '/orcamento/$token'
    | '/admin/'
    | '/minha-viagem/'
    | '/admin/crm/$contactId'
    | '/admin/viagens/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  InteresseRoute: typeof InteresseRoute
  LoginRoute: typeof LoginRoute
  MinhaViagemRoute: typeof MinhaViagemRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  OrcamentoTokenRoute: typeof OrcamentoTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-viagem': {
      id: '/minha-viagem'
      path: '/minha-viagem'
      fullPath: '/minha-viagem'
      preLoaderRoute: typeof MinhaViagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interesse': {
      id: '/interesse'
      path: '/interesse'
      fullPath: '/interesse'
      preLoaderRoute: typeof InteresseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-viagem/': {
      id: '/minha-viagem/'
      path: '/'
      fullPath: '/minha-viagem/'
      preLoaderRoute: typeof MinhaViagemIndexRouteImport
      parentRoute: typeof MinhaViagemRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/orcamento/$token': {
      id: '/orcamento/$token'
      path: '/orcamento/$token'
      fullPath: '/orcamento/$token'
      preLoaderRoute: typeof OrcamentoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-viagem/roteiro': {
      id: '/minha-viagem/roteiro'
      path: '/roteiro'
      fullPath: '/minha-viagem/roteiro'
      preLoaderRoute: typeof MinhaViagemRoteiroRouteImport
      parentRoute: typeof MinhaViagemRoute
    }
    '/minha-viagem/preroteiro': {
      id: '/minha-viagem/preroteiro'
      path: '/preroteiro'
      fullPath: '/minha-viagem/preroteiro'
      preLoaderRoute: typeof MinhaViagemPreroteiroRouteImport
      parentRoute: typeof MinhaViagemRoute
    }
    '/minha-viagem/parceiros': {
      id: '/minha-viagem/parceiros'
      path: '/parceiros'
      fullPath: '/minha-viagem/parceiros'
      preLoaderRoute: typeof MinhaViagemParceirosRouteImport
      parentRoute: typeof MinhaViagemRoute
    }
    '/minha-viagem/mapa': {
      id: '/minha-viagem/mapa'
      path: '/mapa'
      fullPath: '/minha-viagem/mapa'
      preLoaderRoute: typeof MinhaViagemMapaRouteImport
      parentRoute: typeof MinhaViagemRoute
    }
    '/minha-viagem/documentos': {
      id: '/minha-viagem/documentos'
      path: '/documentos'
      fullPath: '/minha-viagem/documentos'
      preLoaderRoute: typeof MinhaViagemDocumentosRouteImport
      parentRoute: typeof MinhaViagemRoute
    }
    '/admin/viagens': {
      id: '/admin/viagens'
      path: '/viagens'
      fullPath: '/admin/viagens'
      preLoaderRoute: typeof AdminViagensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orcamentos': {
      id: '/admin/orcamentos'
      path: '/orcamentos'
      fullPath: '/admin/orcamentos'
      preLoaderRoute: typeof AdminOrcamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notificacoes': {
      id: '/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AdminNotificacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/destinos': {
      id: '/admin/destinos'
      path: '/destinos'
      fullPath: '/admin/destinos'
      preLoaderRoute: typeof AdminDestinosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/viagens/$tripId': {
      id: '/admin/viagens/$tripId'
      path: '/$tripId'
      fullPath: '/admin/viagens/$tripId'
      preLoaderRoute: typeof AdminViagensTripIdRouteImport
      parentRoute: typeof AdminViagensRoute
    }
    '/admin/crm/$contactId': {
      id: '/admin/crm/$contactId'
      path: '/$contactId'
      fullPath: '/admin/crm/$contactId'
      preLoaderRoute: typeof AdminCrmContactIdRouteImport
      parentRoute: typeof AdminCrmRoute
    }
  }
}

interface AdminCrmRouteChildren {
  AdminCrmContactIdRoute: typeof AdminCrmContactIdRoute
}

const AdminCrmRouteChildren: AdminCrmRouteChildren = {
  AdminCrmContactIdRoute: AdminCrmContactIdRoute,
}

const AdminCrmRouteWithChildren = AdminCrmRoute._addFileChildren(
  AdminCrmRouteChildren,
)

interface AdminViagensRouteChildren {
  AdminViagensTripIdRoute: typeof AdminViagensTripIdRoute
}

const AdminViagensRouteChildren: AdminViagensRouteChildren = {
  AdminViagensTripIdRoute: AdminViagensTripIdRoute,
}

const AdminViagensRouteWithChildren = AdminViagensRoute._addFileChildren(
  AdminViagensRouteChildren,
)

interface AdminRouteChildren {
  AdminCrmRoute: typeof AdminCrmRouteWithChildren
  AdminDestinosRoute: typeof AdminDestinosRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminNotificacoesRoute: typeof AdminNotificacoesRoute
  AdminOrcamentosRoute: typeof AdminOrcamentosRoute
  AdminViagensRoute: typeof AdminViagensRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCrmRoute: AdminCrmRouteWithChildren,
  AdminDestinosRoute: AdminDestinosRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminNotificacoesRoute: AdminNotificacoesRoute,
  AdminOrcamentosRoute: AdminOrcamentosRoute,
  AdminViagensRoute: AdminViagensRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MinhaViagemRouteChildren {
  MinhaViagemDocumentosRoute: typeof MinhaViagemDocumentosRoute
  MinhaViagemMapaRoute: typeof MinhaViagemMapaRoute
  MinhaViagemParceirosRoute: typeof MinhaViagemParceirosRoute
  MinhaViagemPreroteiroRoute: typeof MinhaViagemPreroteiroRoute
  MinhaViagemRoteiroRoute: typeof MinhaViagemRoteiroRoute
  MinhaViagemIndexRoute: typeof MinhaViagemIndexRoute
}

const MinhaViagemRouteChildren: MinhaViagemRouteChildren = {
  MinhaViagemDocumentosRoute: MinhaViagemDocumentosRoute,
  MinhaViagemMapaRoute: MinhaViagemMapaRoute,
  MinhaViagemParceirosRoute: MinhaViagemParceirosRoute,
  MinhaViagemPreroteiroRoute: MinhaViagemPreroteiroRoute,
  MinhaViagemRoteiroRoute: MinhaViagemRoteiroRoute,
  MinhaViagemIndexRoute: MinhaViagemIndexRoute,
}

const MinhaViagemRouteWithChildren = MinhaViagemRoute._addFileChildren(
  MinhaViagemRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  InteresseRoute: InteresseRoute,
  LoginRoute: LoginRoute,
  MinhaViagemRoute: MinhaViagemRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  OrcamentoTokenRoute: OrcamentoTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
